### ISSUE TITLE
Class model tidak ter-autoload

### ISSUE THREAD

**Issue by emsifa** [laravolt/indonesia#10]
Barusan coba di L5.3 di ubuntu, dapat error:

```
Class 'Laravolt\Indonesia\Models\Province' not found
```

solusinya saya rename direktori `models` jadi `Models`, cuma mungkin bisa juga ditambahin autoload di composer.json-nya kalau memang mau huruf kecil

**Comment by adhatama** [comment]
Thanks. Issue ini kelewatan dari environment kami. 
Sudah diperbaiki. Silakan update ke versi 0.4 untuk updatenya
