### ISSUE TITLE
Ketiadaan Lisensi

### ISSUE THREAD

**Issue by wisn** [laravolt/indonesia#11]
Halo, saya tidak melihat adanya lisensi di *repository* ini.

Saya lihat informasi lisensi terdapat di composer.json, yaitu [MIT License](http://choosealicense.com/licenses/mit/). Tapi, saya tidak melihat berkas `LICENSE.md` di *repository* ini.
Berhubung lisensi sangat penting untuk "identitas" *repository* ini, saya harap dapat ditambahkan informasinya. Atau, apakah Anda ingin saya yang menambahkannya? Saya tidak keberatan untuk itu. :smile: 

Terima kasih~

**Comment by adhatama** [comment]
Thanks. Sudah ditambahkan

**Comment by ramadani** [comment]
great @adhatama

**Comment by wisn** [comment]
https://github.com/laravolt/indonesia/blob/master/LICENSE#L3

Ups! Mohon diperiksa kembali hak cipta-nya~ :grin:

**Comment by adhatama** [comment]
Ups! Sorry. Ketauan banget copas 😅 
Fixed.
