### ISSUE TITLE
Support Laravel 11

### ISSUE THREAD

**Issue by fdjrr** [laravolt/indonesia#110]

**Comment by novrizal** [comment]
yes, up

**Comment by SamudraPanji** [comment]
Yes, please !!!

**Comment by uyab** [comment]
ETA this week

**Comment by arispujud** [comment]
Waiting Update

**Comment by lakuapik** [comment]
https://github.com/laravolt/indonesia/pull/109

**Comment by rifkitaufik** [comment]
waiting update for laravel 11. and please update the provinces to the latest data in kemendagri

**Comment by uyab** [comment]
#109 merged, new version tagged
