### ISSUE TITLE
result id villages tidak sesuai pada tabel "indonesia_villages" dengan di aplikasi

### ISSUE THREAD

**Issue by muhghazaliakbar** [laravolt/indonesia#12]
saya ingin menampilkan data villages berdasarkan id discrit dengan kueri sbb:
`Indonesia::findDistrict($districtId, ['villages'])`

result "name" dan "discrict_id" nya sudah benar tetapi pada "id" row villages nya sendiri tidak sesuai dengan yang ada pada tabel "villages". Misalnya saya ingin menampilkan data villages berdasarkan discrit_id = 7371040.
result di database:
![screenshot_207](https://cloud.githubusercontent.com/assets/8321936/20293311/2ffb55b6-ab30-11e6-87a0-a4533b7d4ec9.png)
result di aplikasi:
![screenshot_208](https://cloud.githubusercontent.com/assets/8321936/20293316/3ccf73f8-ab30-11e6-8421-06e560137379.png)

**Comment by adhatama** [comment]
Wah kok aneh ya. Aku ndak bisa ngereproduce issue itu.
Database yang digunakan antara yang query dengan yang di aplikasi udah sama kah?

**Comment by muhghazaliakbar** [comment]
di backend kodenya sesuai dengan yang saya catat di atas, `ndonesia::findDistrict($districtId, ['villages'])` saya cuma ikuti dokumentasinya, untuk mencari kelurahan. kemudian saya result dari console.log.

tidak ada olahan lain sepertinya, ini kode saya:
![screenshot_209](https://cloud.githubusercontent.com/assets/8321936/20308692/0984820e-ab80-11e6-9b85-115dcb7737e0.png)

**Comment by muhghazaliakbar** [comment]
makanya saya heran juga :/

**Comment by abangrephol** [comment]
mungkin karena limit integer yang hanya sampai 2,147,483,647
solusi yang saya temukan dengan menambah variable 
`public $incrementing = false;`
pada model Village

**Comment by uyab** [comment]
Fixed in v0.8

PS: Ok, saya tahu issue ini sudah berumur sekitar 1,5 tahun, tetapi itu justru menjadikan bug fixingnya lebih greget ^_^, cc @adhatama

**Comment by adhatama** [comment]
@uyab jadi masalahnya apa?

**Comment by uyab** [comment]
@adhatama Fokus ke angka cantik `2,147,483,647`.

- Itu merupakan batas maksimal tipe data `int` di PHP 32 bit.
- `int` merupakan tipe data default untuk primary key di Eloquent.
- Makanya ketika dicasting, ID village (yang notabene angkanya besar-besar) selalu mentok di `2,147,483,647`. Kalau yang ID nya dibawah itu pasti tidak ada masalah.
- Solusinya, cek commitan terakhir 😄

**Comment by uyab** [comment]
Kenapa kita tidak bisa reproduce, karena laptopnya sudah 64 bit.
