### ISSUE TITLE
versi README.md untuk Bahasa Inggris

### ISSUE THREAD

**Issue by indrakaw** [laravolt/indonesia#14]
_Be international_, masukan saya adalah adanya versi penjelasan dalam bahasa Inggris untuk repo ini. Anda bisa buat sisipan, misal: `README_en.md` untuk readme dalam bahasa inggris.

Mengapa? Agar mudah dipakai oleh non-Indonesian users, pastinya.

**Comment by adhatama** [comment]
Sure. It would be nice to have that.
And I will gladly accept pull request to this 😃
