### ISSUE TITLE
Doesn't work on laravel 5.4

### ISSUE THREAD

**Issue by amalari** [laravolt/indonesia#20]
please fix this issue, thanks

**Comment by ladhadha** [comment]
Please give more information how it's doesn't work on Laravel 5.4

**Comment by adibfirman** [comment]
hei @ladhadha i just used this before, i use this package for my project, and then the file migration nothing import, why?\

**Comment by uyab** [comment]
@adibfirman and @amalari, please provide more detailed information, i.e screnshoot, error message, etc. I just tried install this package on fresh Laravel 5.4, all is fine.

**Comment by adibfirman** [comment]
@uyab hmmm okay i will try again, thank you very much
