### ISSUE TITLE
Class 'Laravolt\Indonesia' not found

### ISSUE THREAD

**Issue by mulyawansentosa** [laravolt/indonesia#27]
I got this error Class 'Laravolt\Indonesia' not found when call it from my controller.
We have followed your procedure to install this. But the error occur. I use Laravel 5.4. How to fix this?
thank you.

**Comment by uyab** [comment]
Can you provide some snippets?

**Comment by daemswibowo** [comment]
Same problem here. I use Laravel 5.5

![screen shot 2018-03-24 at 13 30 32](https://user-images.githubusercontent.com/9953444/37860779-8cc3c4e2-2f67-11e8-86b1-ce2d6a6413e7.png)

**Comment by uyab** [comment]
I think you import the wrong path, it should use Indonesia, not use Laravolt/Indonesia
