### ISSUE TITLE
Function Naming

### ISSUE THREAD

**Issue by uyab** [laravolt/indonesia#3]
Rename:
* getProvinces()
* getProvincesPaginate()
* ...

To:
* allProvinces()
* paginateProvinces()
* ...

This will make this package more consistent with Laravel, e.g: `$model->all()` and `$model->paginate()`

**Comment by uyab** [comment]
And also:

* getProvince($id) -> findProvince($id)
* getCity($id) -> findCity($id)
* ....

**Comment by adhatama** [comment]
Nice! I'm having a tough time figuring out the names before
