### ISSUE TITLE
Unit Testing Error

### ISSUE THREAD

**Issue by nafiesl** [laravolt/indonesia#31]
Halo @laravolt, sebelumnya saya terima kasih karena Laravolt sudah membuat package ini. Saya ingin ikut kontribusi ke package ini. Ketika clone project ke localhost, kemudian melakukan `composer install`, berhasil.

Tetapi ketika menjalankan unit test nya, ketemu error ini.

![Selection_190410008](https://user-images.githubusercontent.com/8721551/55885303-492b0680-5bdc-11e9-84ef-99e261164a63.jpg)

Kemudian saya mencoba install package `orchestra/database` yang dimaksud, tetapi gagal karena versinya tidak cocok.

Mohon petunjuknya apa yang harus dilakukan agar testingnya passed?

Saat ini saya menggunakan:
- php versi 7.2.13,
- web server Apache/2.4.18 (Ubuntu) 
- OS Linux mint 18.3

Terima kasih sebelumnya.

**Comment by uyab** [comment]
Halo @nafiesl , package ini dibuat sudah cukup lama, dengan berdasar Laravel 5.2 dan PHP 5.5 pada waktu itu. Kalau berminat, mungkin kita naikkan dulu beberapa dependensi, misal kita target ke PHP 7.1 dan Laravel 5.7, otomatis beberapa package seperti phpunit, testbench, juga perlu disesuaikan.

**Comment by nafiesl** [comment]
Ok siap mas @uyab saya akan coba bikin testingnya passed di local repo saya dulu ya mas. Kalau sudah passed akan saya buat PR.

**Comment by uyab** [comment]
Saya barusan update beberapa dependencies, kalau mau lanjutin dari branch `dev` saja. Errornya berubah jadi kekurangan memory ^_^

**Comment by nafiesl** [comment]
Ok siap, akan saya coba pull nanti mas.

**Comment by nafiesl** [comment]
Mantap mas @uyab, sudah hijau testingnya dengan menggunakan branch `dev`.

![Selection_190411001](https://user-images.githubusercontent.com/8721551/55945585-acb94080-5c7d-11e9-81a3-8da245206fcf.jpg)
