### ISSUE TITLE
Non Static 

### ISSUE THREAD

**Issue by inoex135** [laravolt/indonesia#37]
![image](https://user-images.githubusercontent.com/244285/63635510-9f7d7b00-c68d-11e9-898b-463a0fd5daf0.png)

Di dokumentasinya dipanggil static, tapi pas dipanggil static, dia bilang tidak bisa dipanggil static. 

Saya lihat di source codenya fungsi itu memang tidak static

**Comment by inoex135** [comment]
![image](https://user-images.githubusercontent.com/244285/63635523-c89e0b80-c68d-11e9-9e61-2a3b1ca0072b.png)

ini screenshot dari dokumentasi penggunaan

**Comment by cacing69** [comment]
ngga mas, kalo yang ada di dokumentasi itu merupakan hasil alias kelas yang ada di config, seperti nya mas cuman salah masukkin kelas nya aja. harus nya mas import yang dari Facade atau alias nya dengan cara begini

`use Indonesia;`

dengan syarat mas udah ngedaftarin Alias di file app.php
![Screenshot_340](https://user-images.githubusercontent.com/36250619/63659013-1d01d200-c7d9-11e9-8a44-ddb0eb70761e.png)

dari hasil percobaan saya ini bisa mas
![carbon](https://user-images.githubusercontent.com/36250619/63659081-7833c480-c7d9-11e9-814b-c1849ee2ce41.png)

**Comment by uyab** [comment]
Terima kasih @cacing69 atas penjelasannya,  saya perbaiki di v0.13 dengan merename class `Indonesia` menjadi `IndonesiaService`.
