### ISSUE TITLE
Seeder tidak berjalan di production

### ISSUE THREAD

**Issue by yogs22** [laravolt/indonesia#41]
Ketika menajalankan seed di production. Seeder tidak berjalan, hanya stuck setelah perintah dijalankan

**Comment by rizkyarlin** [comment]
Di local bisa tp di production bisa? `.env` nya udah bener gak tuh?

"stuck setelah perintah dijalankan", gak ada pesan sama sekali? Kalau dibiarin gak ada database timeout?

**Comment by yogs22** [comment]
- ```.env``` sudah benar

- tidak ada pesan sama sekali, database juga tidak timeout. Kalo env sudah production ada konfirmasi untuk melakukan seed. Nah sementara disini tidak ada konfirmasi. Mungkin menyangkut disni mas

**Comment by yogs22** [comment]
![image](https://user-images.githubusercontent.com/25165999/65943242-2fff6600-e459-11e9-8271-6ad275ad9697.png)
Jika seed di production ada konfirmasi seperti ini

**Comment by rizkiiramdani** [comment]
### saya mencoba menjalankan di laravel 6
**composer require laravolt/indonesia**
`=> php artisan vendor:publish => Laravolt\Indonesia\ServiceProvider`
`=> lalu di config => laravolt => indonesia (jika ingin menghilangkan table_prefix)`
![Screen Shot 2019-10-01 at 15 02 40](https://user-images.githubusercontent.com/29448363/65944794-b23d5980-e45c-11e9-836f-12c4326cefcc.png)

`=> php artisan migrate`
![Screen Shot 2019-10-01 at 15 09 41](https://user-images.githubusercontent.com/29448363/65945241-c59cf480-e45d-11e9-95c9-106700d0aa7f.png)

_ada error saat generate mengatakan ada kesalahan, namun ketika cek database code yang dijalankan berjalan dengan baik, adakah solusi seperti masalah saya biar saat migrasi tidak menampilkan kesalahan?_

**Comment by uyab** [comment]
bisa share file seedernya?

**Comment by yogs22** [comment]
saya menjalankan pa `laravolt:indonesia:seed`

**Comment by uyab** [comment]
Saya ada update di branch `master`, bisa bantu cek apakah berhasil?

**Comment by rizkyarlin** [comment]
mas @uyab, e213ea28baf0a9b6407c31963c6a9d6e6d14f789 ngefek ke `IndonesiaTest@it_can_call_indonesia_service()`. 

sepertinya kita gak bisa pake `'SET FOREIGN_KEY_CHECKS=0;'` di sqlite

**Comment by uyab** [comment]
Fixed in v0.18

**Comment by yogs22** [comment]
![image](https://user-images.githubusercontent.com/25165999/66013482-91751280-e4f5-11e9-9ab6-f2a178fd02be.png)

Masih tetep stuck, saya udah coba composer update

**Comment by uyab** [comment]
bisa cek laravolt/indonesia nya versi berapa?

**Comment by uyab** [comment]
dan database yang dipakai apa?

**Comment by yogs22** [comment]
Ternyata masih v0.16 setelah saya composer update
pake mysql mas

**Comment by yogs22** [comment]
Masih stuck dan saya sudah mencoba upgrade ke v0.18

**Comment by uyab** [comment]
coba jalankan secara manual:
`php artisan db:seed --class="Laravolt\Indonesia\Seeds\DatabaseSeeder"`

**Comment by yogs22** [comment]
![image](https://user-images.githubusercontent.com/25165999/66014149-f29de580-e4f7-11e9-9d6a-f1904d3e2ac2.png)

Setelah saya ubah menjadi `local` seed berjalan lancar

**Comment by uyab** [comment]
sip, ketahuan masalahnya. Kalau di production, memanggil db:seed akan muncul prompt. Inilah yang bikin perintah `Artisan::call()` jadi stuck. Fixed in v0.19.

**Comment by yogs22** [comment]
Iya mas, seperti yang saya jelaskan di atas, kalo production ada konfirmasi untuk melakukan seed.
Oke Terima Kasih banyak mas Bayu :)
