### ISSUE TITLE
[usul] penambahan data latitude longitude

### ISSUE THREAD

**Issue by lakuapik** [laravolt/indonesia#42]
Halo bung,

Saya tertarik dengan projek ini. Keren 👍

Kemarin saya ada projek yang pakai data-data ini, tapi disisi lain perlu ada data letak latitude longitude di bagian kota/kab (district). Saya cari-cari tidak ada, lalu saya coba generate sendiri waktu itu pakai api google geocoding.

Ini hasil filenya yang sudah ada latitude longitude: 
https://archive.org/download/administrative_indonesia_districts_with_lat_lng/administrative_indonesia_districts_with_lat_lng.csv

Kira-kira, saya ada usul nih. Data yg sekarang ditambahkan letak latitude longitudenya. Saat ini saya hanya ada yang district, kalau oke, nanti bisa di open issue biar teman-teman lain bisa membantu melengkapi.

Terima Kasih.

**Comment by rizkyarlin** [comment]
ini city_id-nya  dari repo ini kan yah?

**Comment by rizkyarlin** [comment]
Ini keren sih mas @uyab, drpd yg make harus manggil API google geocoding setiap mau ambil latitude longitude. Ini juga bisa ngebantu programmer yg belum punya akses ke API Geocoding, mungkin karena gak punya Credit Card.

Untuk generatenya sepertinya bagus buat repo sendiri kali yah?

**Comment by uyab** [comment]
Sip, kita sudah punya kolom `meta` yang memang didesain untuk menyimpan data pendukung (yang bisa jadi setiap developer berbeda kebutuhannya). Saya sepakat untuk membuat repo terpisah, bisa di akun masing-masing (nanti dimention di readme) atau tetap di org laravolt. 

Sampai sini ada tanggapan? Kalau oke, bisa langsung ekseskusi.

**Comment by lakuapik** [comment]
Mantap, saya setuju bung.

**Comment by rizkyarlin** [comment]
Di laravolt aja mas

**Comment by uyab** [comment]
Saya minta bantuan @lakuapik dan/atau @rizkyarlin ya untuk bikin MVP nya, nanti kalau sudah jadi tinggal ditransfer reponya. Sepertinya sudah pada paham kan teknisnya?

Paling nitip dibikin command untuk seed datanya, misal `laravolt:indonesia:sync-coordinate`. Bisa jadi nanti ada yang mau bikin `sync-populasi`, `sync-luas-wilayah`, dan lain-lain.

**Comment by rizkyarlin** [comment]
mas @lakuapik aja yg buat reponya, karena doi udah ada codingan untuk API Geocodingnya

**Comment by lakuapik** [comment]
bung @rizkyarlin saja gmn yang init repo dan boilerplatenya, karena saya blm tahu gimana standardnya laravolt. Nanti kalau sudah ada saya bisa PR.

**Comment by uyab** [comment]
Ada yang sudah bergerak kah? Btw saya sedang ngoprek https://developers.google.com/maps/documentation/geocoding/start, sepertinya saya lebih percaya data dari API Google 😅 

Nanti kalau semua sudah dapat datanya, saya share data mentahnya.

cc @anandiamy

**Comment by rizkyarlin** [comment]
mas @lakuapik jg pakai itu kok mas @uyab

**Comment by uyab** [comment]
Wah iya bener sekali, saya ke-skip bagian google geocodingnya. Saya dari pagi generate koordinat, baru dapat 82%:

![image](https://user-images.githubusercontent.com/149716/66469183-a2072900-eab1-11e9-8a36-53a8b3f02845.png)

Saya sudah siapkan repo terpisah, https://github.com/laravolt/indonesia-coordinate, nanti data mentahnya diupload kesitu dan ditambahkan command:
1. `laravolt:indonesia:seed-coordinate` untuk membaca data mentah lalu memasukkan ke database
1. `laravolt:Indonesia:sync-coordinate` untuk memanggil API geocoding dan memperbarui data mentah

Ada tanggapan kah?

**Comment by anandiamy** [comment]
kenapa gak pakai repo ini aja ?

**Comment by uyab** [comment]
Hmm, pertanyaan bagus, kenapa ya dulu indonesia-logo dipisah 🤔

**Comment by rizkyarlin** [comment]
repo ini aja kali yah, saya dulu mikirnya bakal agak beda arahnya, tp dgn yg dilakukan mas uyab sepertinya oke aja untuk langsung di repo ini

**Comment by uyab** [comment]
updated di master , bisa coba jalankan ulang `laravolt:indonesia:seed` dan mungkin bantu random check memastikan koordinatnya benar

**Comment by lakuapik** [comment]
mantap nih, udah dibikin ya @uyab @rizkyarlin 

tapi ini kita masih harus masukan api key dari google geocodenya ya? 
saya pikir nanti ada resource file untuk coordinatesnya dan pas di seed tinggal masukin data lat lng ke metanya.

**Comment by uyab** [comment]
@lakuapik 

`laravolt:indonesia:seed` bakal langsung seed data koordinat dari CSV.

`laravolt:indonesia:sync-coordinate` baru butuh api key.

**Comment by anandiamy** [comment]
nah data koordinat nya masukin package ini aja sih mas

supaya gak usah ngejalanin `laravolt:indonesia:sync-coordinate`

**Comment by uyab** [comment]
Ini kan sudah masuk, coba cek branch master @anandiamy 😅
