### ISSUE TITLE
Please fix bug for lumen

### ISSUE THREAD

**Issue by shadowgroundz** [laravolt/indonesia#48]
Saya pakai lumen 5.7. ada beberapa bug yang saya temukan
1. File config tidak berjalan. Saya ingin menghilangkan prefix table nya dari file config, ternyata tidak bisa
2. Untuk seeder seperti cities, district dll error undefined function now(). Mungkin bisa diganti dengan date("Y-m-d H:i:s")

Untuk yang baru ketemu itu saja. Saya belum coba eloquent nya karena kebetulan lumen tidak ada tinker. Semoga tmbah baik lib nya. Terimakasih

**Comment by shadowgroundz** [comment]
Saya tidak bisa mengakses data dari model. Hasil nya attributes nya protected. Bagaimana cara mengaksesnya? Terimakasih


object(Laravolt\Indonesia\Models\District)#7205 (27) {
  ["table":protected]=>
  string(9) "districts"
  ["casts":protected]=>
  array(1) {
    ["meta"]=>
    string(5) "array"
  }
  ["timestamps"]=>
  bool(false)
  ["keyType":protected]=>
  string(6) "string"
  ["searchableColumns":protected]=>
  array(2) {
    [0]=>
    string(2) "id"
    [1]=>
    string(4) "name"
  }
  ["connection":protected]=>
  string(5) "mysql"
  ["primaryKey":protected]=>
  string(2) "id"
  ["incrementing"]=>
  bool(true)
  ["with":protected]=>
  array(0) {
  }
  ["withCount":protected]=>
  array(0) {
  }
  ["perPage":protected]=>
  int(15)
  ["exists"]=>
  bool(true)
  ["wasRecentlyCreated"]=>
  bool(false)
  ["attributes":protected]=>
  array(6) {
    ["id"]=>
    string(7) "1101010"
    ["city_id"]=>
    string(4) "1101"
    ["name"]=>
    string(14) "TEUPAH SELATAN"
    ["meta"]=>
    string(38) "{"lat":"2.3860301","long":"96.429036"}"
    ["created_at"]=>
    string(19) "2019-11-03 21:25:23"
    ["updated_at"]=>
    string(19) "2019-11-03 21:25:23"
  }
  ["original":protected]=>
  array(6) {
    ["id"]=>
    string(7) "1101010"
    ["city_id"]=>
    string(4) "1101"
    ["name"]=>
    string(14) "TEUPAH SELATAN"
    ["meta"]=>
    string(38) "{"lat":"2.3860301","long":"96.429036"}"
    ["created_at"]=>
    string(19) "2019-11-03 21:25:23"
    ["updated_at"]=>
    string(19) "2019-11-03 21:25:23"
  }
  ["changes":protected]=>
  array(0) {
  }
  ["dates":protected]=>
  array(0) {
  }
  ["dateFormat":protected]=>
  NULL
  ["appends":protected]=>
  array(0) {
  }
  ["dispatchesEvents":protected]=>
  array(0) {
  }
  ["observables":protected]=>
  array(0) {
  }
  ["relations":protected]=>
  array(0) {
  }
  ["touches":protected]=>
  array(0) {
  }
  ["hidden":protected]=>
  array(0) {
  }
  ["visible":protected]=>
  array(0) {
  }
  ["fillable":protected]=>
  array(0) {
  }
  ["guarded":protected]=>
  array(1) {
    [0]=>
    string(1) "*"
  }
}

**Comment by rizkyarlin** [comment]
> Saya tidak bisa mengakses data dari model. Hasil nya attributes nya protected. Bagaimana cara mengaksesnya? Terimakasih
> 
> object(Laravolt\Indonesia\Models\District)#7205 (27) {
> ["table":protected]=>
> string(9) "districts"
> ["casts":protected]=>
> array(1) {
> ["meta"]=>
> string(5) "array"
> }
> ["timestamps"]=>
> bool(false)
> ["keyType":protected]=>
> string(6) "string"
> ["searchableColumns":protected]=>
> array(2) {
> [0]=>
> string(2) "id"
> [1]=>
> string(4) "name"
> }
> ["connection":protected]=>
> string(5) "mysql"
> ["primaryKey":protected]=>
> string(2) "id"
> ["incrementing"]=>
> bool(true)
> ["with":protected]=>
> array(0) {
> }
> ["withCount":protected]=>
> array(0) {
> }
> ["perPage":protected]=>
> int(15)
> ["exists"]=>
> bool(true)
> ["wasRecentlyCreated"]=>
> bool(false)
> ["attributes":protected]=>
> array(6) {
> ["id"]=>
> string(7) "1101010"
> ["city_id"]=>
> string(4) "1101"
> ["name"]=>
> string(14) "TEUPAH SELATAN"
> ["meta"]=>
> string(38) "{"lat":"2.3860301","long":"96.429036"}"
> ["created_at"]=>
> string(19) "2019-11-03 21:25:23"
> ["updated_at"]=>
> string(19) "2019-11-03 21:25:23"
> }
> ["original":protected]=>
> array(6) {
> ["id"]=>
> string(7) "1101010"
> ["city_id"]=>
> string(4) "1101"
> ["name"]=>
> string(14) "TEUPAH SELATAN"
> ["meta"]=>
> string(38) "{"lat":"2.3860301","long":"96.429036"}"
> ["created_at"]=>
> string(19) "2019-11-03 21:25:23"
> ["updated_at"]=>
> string(19) "2019-11-03 21:25:23"
> }
> ["changes":protected]=>
> array(0) {
> }
> ["dates":protected]=>
> array(0) {
> }
> ["dateFormat":protected]=>
> NULL
> ["appends":protected]=>
> array(0) {
> }
> ["dispatchesEvents":protected]=>
> array(0) {
> }
> ["observables":protected]=>
> array(0) {
> }
> ["relations":protected]=>
> array(0) {
> }
> ["touches":protected]=>
> array(0) {
> }
> ["hidden":protected]=>
> array(0) {
> }
> ["visible":protected]=>
> array(0) {
> }
> ["fillable":protected]=>
> array(0) {
> }
> ["guarded":protected]=>
> array(1) {
> [0]=>
> string(1) "*"
> }
> }

ini buatin issue baru

**Comment by rizkyarlin** [comment]
Tolong issue nya dipisah mas

**Comment by shadowgroundz** [comment]
Sudah saya pisah ya

**Comment by uyab** [comment]
Terima kasih atas isunya @shadowgroundz , sudah saya tag versi terbaru untuk mengakomodir 2 isu di atas. Terkait config, silakan baca ulang petunjuknya di https://github.com/laravolt/indonesia#daftarkan-service-provider-dan-facade-untuk-lumen karena ada penyesuaian.
