### ISSUE TITLE
Tidak bisa akses data dengan menggunakan lumen

### ISSUE THREAD

**Issue by shadowgroundz** [laravolt/indonesia#49]
Saya tidak bisa mengakses data dari model. Hasil nya attributes nya protected. Bagaimana cara mengaksesnya? Terimakasih

object(Laravolt\Indonesia\Models\District)#7205 (27) {
["table":protected]=>
string(9) "districts"
["casts":protected]=>
array(1) {
["meta"]=>
string(5) "array"
}
["timestamps"]=>
bool(false)
["keyType":protected]=>
string(6) "string"
["searchableColumns":protected]=>
array(2) {
[0]=>
string(2) "id"
[1]=>
string(4) "name"
}
["connection":protected]=>
string(5) "mysql"
["primaryKey":protected]=>
string(2) "id"
["incrementing"]=>
bool(true)
["with":protected]=>
array(0) {
}
["withCount":protected]=>
array(0) {
}
["perPage":protected]=>
int(15)
["exists"]=>
bool(true)
["wasRecentlyCreated"]=>
bool(false)
["attributes":protected]=>
array(6) {
["id"]=>
string(7) "1101010"
["city_id"]=>
string(4) "1101"
["name"]=>
string(14) "TEUPAH SELATAN"
["meta"]=>
string(38) "{"lat":"2.3860301","long":"96.429036"}"
["created_at"]=>
string(19) "2019-11-03 21:25:23"
["updated_at"]=>
string(19) "2019-11-03 21:25:23"
}
["original":protected]=>
array(6) {
["id"]=>
string(7) "1101010"
["city_id"]=>
string(4) "1101"
["name"]=>
string(14) "TEUPAH SELATAN"
["meta"]=>
string(38) "{"lat":"2.3860301","long":"96.429036"}"
["created_at"]=>
string(19) "2019-11-03 21:25:23"
["updated_at"]=>
string(19) "2019-11-03 21:25:23"
}
["changes":protected]=>
array(0) {
}
["dates":protected]=>
array(0) {
}
["dateFormat":protected]=>
NULL
["appends":protected]=>
array(0) {
}
["dispatchesEvents":protected]=>
array(0) {
}
["observables":protected]=>
array(0) {
}
["relations":protected]=>
array(0) {
}
["touches":protected]=>
array(0) {
}
["hidden":protected]=>
array(0) {
}
["visible":protected]=>
array(0) {
}
["fillable":protected]=>
array(0) {
}
["guarded":protected]=>
array(1) {
[0]=>
string(1) "*"
}
}

**Comment by rizkyarlin** [comment]
cara mengaksesnya bgmn?

**Comment by shadowgroundz** [comment]
Sesuai dengan penggunaan yang anda berikan di https://github.com/laravolt/indonesia#penggunaan. Hasil tersebut saya vardump

**Comment by uyab** [comment]
Hasil dari fungsi-fungsi yang disediakan facade `Indonesia` bertipe Eloquent Model (https://laravel.com/docs/5.7/eloquent). Silakan dibaca dan dipahami bagaimana cara mengakses atributnya. Kalau di-dump, hasilnya memang seperti itu.

Jika ingin versi sederhana, bisa langsung dikonversi ke array saja, seperti contoh di bawah:
```php
Indonesia::findProvince(11, ['cities'])->toArray()
```
Silakan di-dump untuk melihat hasilnya :)
