### ISSUE TITLE
Search by keyword

### ISSUE THREAD

**Issue by uyab** [laravolt/indonesia#5]
**Use case**
Autocomplete via ajax. Usually when we built some form input that ask user to select specific village, we force user to select province, and then city, and then district, and then village. I want to get rid all of those step, and just let user to type their village directly into textbox, and then system will provide suggestions via autocomplete.

**Comment by uyab** [comment]
I think we can implement it as chainable method for each content type or for overall, e.g:

```php
// specific content type
Indonesia::search('sra')->getProvince();
Indonesia::search('karang')->paginateProvince();
Indonesia::search('solo')->getCities();

// all content type
Indonesia::search('kotaba')->get();
```

**Comment by adhatama** [comment]
Do you mean the search from [Laravel Scout](https://www.laravel.com/docs/5.3/scout#searching) in Laravel 5.3?

**Comment by uyab** [comment]
How it work under the hood was up to you, just make the API consistent with
Laravel.

**Comment by uyab** [comment]
Simple search using LIKE might be enough.

**Comment by adhatama** [comment]
@uyab What do you think about this results for search all? Which is better?
```
[
    'provinces' => Collections,
    'cities' => Collections
    ...
]
```

or

```
[
    Province Object,
    Province Object,
    City Object,
    City Object,
    ...
]
```

**Comment by uyab** [comment]
The second is better
