### ISSUE TITLE
Mohon perbaikan penamaan

### ISSUE THREAD

**Issue by shadowgroundz** [laravolt/indonesia#52]
Mungkin untuk penamaan seperti provinsi (yang baru saya ketemu) bisa di ubah. Seperti Sumatra, menurut saya seharusnya SUMATERA. Soalnya saya mau gabungkan dengan rajaongkir, penamaan nya

**Comment by uyab** [comment]
Setelah saya cek di situs-situs resmi pemerintahan, ternyata memang benar harusnya SUMATERA.
Bisa dibantu perbaikannya dengan Pull Request?
