### ISSUE TITLE
Terinstallnya package yang tidak diinginkan

### ISSUE THREAD

**Issue by yogs22** [laravolt/indonesia#54]
#ASK 
Ketika saya require package laravolt/indonesia kenapa ada beberapa package yang ikut terinstall, sebagai contoh package mdf dan easy excel. Bagaimana cara untuk menghapus package tersebut dan hanya saya spesifikan untuk package seeder data wilayah indonesia?

Terimakasih

**Comment by uyab** [comment]
Ini karena ada package laravolt/suitable. Bener sih, package tersebut tidak digunakan kalau hanya sekedar butuh import data. Saya agendakan untuk diremove saja, lebih cocok masuk ke suggestions.

**Comment by yogs22** [comment]
Oke mas moga segera bisa diupdate,

**Comment by yogs22** [comment]
#ASK Bagaimana menghilangkan package laravolt/suitable ?

**Comment by uyab** [comment]
updated di v0.25
