### ISSUE TITLE
Tidak berjalan dengan baik di laravel 6

### ISSUE THREAD

**Issue by abela-a** [laravolt/indonesia#55]

**Comment by uyab** [comment]
Tidak baiknya seperti apa ya? Bisa kasih deskripsi lebih jelas?

**Comment by rickyanwar** [comment]
![Uploading Screenshot from 2019-12-30 16-48-40.png…]()
saya install lravaolt dan mengikuti langkah di readmenya ,tapi kenapa di config/ saya tidak menemukan config/laravolt.php ? 

dan juga ketika menambahkan $app->configure('laravolt'); di bootstrap/app.php saya mendaptkan error 
> Uncaught Error: Call to undefined method Illuminate\Foundation\Application::configure()

**Comment by rickyanwar** [comment]
![Screenshot from 2019-12-30 17-00-55](https://user-images.githubusercontent.com/36995966/71575000-2bb11a80-2b26-11ea-9ec4-7ea34951a862.png)
![Screenshot from 2019-12-30 17-01-17](https://user-images.githubusercontent.com/36995966/71575013-366baf80-2b26-11ea-9639-80f2d951065c.png)
saya mengalmi hal yang sama pada laravel 6.0 ,data tiak di tampilkan
