### ISSUE TITLE
Pakek untuk laravel 5.6 tidak Support

### ISSUE THREAD

**Issue by addeye** [laravolt/indonesia#58]
Muncul error

`Problem 1
    - Installation request for laravolt/indonesia ^0.25.0 -> satisfiable by laravolt/indonesia[v0.25].
    - Conclusion: remove laravel/framework v5.6.39
    - Conclusion: don't install laravel/framework v5.6.39
    - laravolt/indonesia v0.25 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].`

**Comment by uyab** [comment]
Silakan pakai versi https://packagist.org/packages/laravolt/indonesia#v0.24

**Comment by addeye** [comment]
`Problem 1
    - Installation request for laravolt/indonesia ^0.24.0 -> satisfiable by laravolt/indonesia[v0.24].
    - Conclusion: remove laravel/framework v5.6.39
    - Conclusion: don't install laravel/framework v5.6.39
    - laravolt/indonesia v0.24 requires illuminate/support 5.7.*|5.8.*|6.* -> satisfiable by illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].`

Tetap saja tidak berhasil. @uyab
