### ISSUE TITLE
Laravolt Suitable Dependency

### ISSUE THREAD

**Issue by saputradharma** [laravolt/indonesia#59]
Just asking, why this package require `laravolt/suitable` ? It's exist on `require`. Actually I got an issue with package discovery, I use `laravel/snappy` for pdf, but after installing `laravolt/indonesia` my PDF broken, found out that the root cause is `laravolt/suitable` define it's own PDF library (`MPDF`). 

I use laravolt/indonesia:0.24

**Comment by uyab** [comment]
https://github.com/laravolt/indonesia/issues/54
