### ISSUE TITLE
Saya coba Install package pada laravel 6 terjadi error kenapa ya? 

### ISSUE THREAD

**Issue by riftjumper** [laravolt/indonesia#72]
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravolt/indonesia ^0.29 -> satisfiable by laravolt/indonesia[v0.29].
    - Conclusion: don't install laravel/framework v6.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.6 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.7 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.8 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.9 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.10 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.11 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.12 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.13 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.14 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.15 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.16 (conflict analysis result)
    - Conclusion: don't install laravel/framework v6.20.0 (conflict analysis result)
    - laravolt/indonesia v0.29 requires illuminate/support ^8.0 -> satisfiable by illuminate/support[v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v8.0.0, ..., 8.x-dev], laravel/framework[v6.20.0, ..., 6.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^6.20 -> satisfiable by laravel/framework[v6.20.0, ..., 6.x-dev].`

**Comment by uyab** [comment]
Untuk Laravel 6, silakan pakai versi 0.26 (https://packagist.org/packages/laravolt/indonesia#v0.26).

```bash
composer require laravolt/indonesia:0.26
```
