### ISSUE TITLE
Call to undefined method Laravolt\Indonesia\Indonesia

### ISSUE THREAD

**Issue by lukmanbagus** [laravolt/indonesia#8]
pada laravel versi 5.2 tidak bisa dijalan, mohon bantuannya gan

[Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Laravolt\Indonesia\Indonesia::allVillages()

![laravolt](https://cloud.githubusercontent.com/assets/12353055/18334330/deada9e4-75a0-11e6-8738-59638dc2daf1.png)

**Comment by lukmanbagus** [comment]
Sudah Solved gan, setelah saya lihat dokumentasi pada direktori **_vendor/laravolt/indonesia/src/README.md_** ternyata cara penggunaan berbeda dari dokumentasi yang tertulis di halaman github.
Contoh: untuk memanggil provinsi menggunakan getProvinces() pada halaman github tertulis allProvinces()

Terimaksih atas package nya nice work !

**Comment by adhatama** [comment]
Sip gan thanks atas laporannya.

Tapi tolong update ke versi `0.3` gan. Barusan ane release.
Yang terbaru seharusnya memang menggunakan api seperti yang ada di `README.md`

**Comment by lukmanbagus** [comment]
Oke gan
