### ISSUE TITLE
Data tambahan untuk tiap tabel

### ISSUE THREAD

**Issue by uyab** [laravolt/indonesia#9]
**Contoh Kasus**
Jon ingin menambahkan data kode pos di tabel desa/kelurahan. Di tempat lain, Dodo ingin menambahkan data luas wilayah dan jumlah penduduk untuk semua provinsi. 

**Usulan Solusi**
Tambahkan satu kolom `json` di tiap tabel, yang bisa diisi sesuai kebutuhan oleh masing-masing developer.

**Comment by PetengDedet** [comment]
+1

**Comment by uyab** [comment]
Tambahkan sebuah kolom `meta` dengan tipe data `JSON` di tiap-tiap tabel.

**Comment by darkcyber** [comment]
apa tipe data JSON ada di semua versi manajemen database mas?

**Comment by uyab** [comment]
@darkcyber iya, tidak semua DBMS punya, amannya jadi `text` saja? Tapi kalau text, tidak bisa memanfaatkan fungsi-fungsi built in JSON column, seperti searching dan virtual column. 🤔

**Comment by darkcyber** [comment]
saya dulu ada kasus mirip, saya buat text tapi input ke db nya harus di serialize dulu, begitupun ketika mau ditampilkan harus di unserialize, tapi gak yakin itu best practice. tapi kalo di generalkan memang seperti itu deh seharusnya.

**Comment by Titonu** [comment]
untuk menambahkan data kodepos untuk di table Villages apakah ada opsinya ya?

**Comment by uyab** [comment]
@Titonu saat ini belum ada, silakan bikin migration dan seeder sendiri

**Comment by cacing69** [comment]
kalo di siapin table meta kira kira bisa ngga ya mas ?

```
indonesia_..
..

indonesia_meta
..

indonesia_has_meta
..
```

**Comment by uyab** [comment]
Saya prefer pake json column saja sih, bakal lebih mudah ga?

**Comment by cacing69** [comment]
@uyab  berarti di masing masing nambah 1 kolom gitu ya mas, tapi handling buat yang ga support json column jadinya gimana ya mas seprti kata mas di atas

**Comment by rizkyarlin** [comment]
soal fungsi built-in json column. kalau di migration-nya dibuatin logic untuk membaca rdbmsnya apa, terus kalau support column nya dibuat json, tapi kalau tdk support dibuat text?

**Comment by uyab** [comment]
@rizkyarlin defaultnya dibikin `text` aja kalau gitu, kalau butuh json bisa publish migration + edit sendiri.

**Comment by uyab** [comment]
Saya biasa memakai library https://github.com/spatie/laravel-schemaless-attributes untuk handling schemaless column

**Comment by uyab** [comment]
Tq $
