### ISSUE TITLE
Class "Geocoder" not found

### ISSUE THREAD

**Issue by adjarriawan** [laravolt/indonesia#97]
Prosedur
1. Upgrade dari versi 0.27 ke 0.32
2. Jalankan perintah `php artisan laravolt:indonesia:sync-coordinate`
![Screenshot 2022-09-28 at 11 15 57](https://user-images.githubusercontent.com/37354675/192679454-1455450d-a29f-4395-947d-9e4d16a574ec.png)

**Comment by uyab** [comment]
Ini perlu install package tambahan:
![image](https://user-images.githubusercontent.com/149716/192684145-fc28f664-2357-4e54-bd42-aa1e582d3148.png)
